import * as THREE from './vendor/three.module.js';
import {objects,timeline,knowledge} from './data.js';
import {setupHandControls} from './hands.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let selected='earth',group='solar',zoom=1,rotating=!matchMedia('(prefers-reduced-motion:reduce)').matches,renderer,toastTimer;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,1000);camera.position.set(0,0,8.6);
const globe=new THREE.Group();globe.position.y=.67;scene.add(globe);scene.add(new THREE.AmbientLight(0xadc8eb,1.4));const sun=new THREE.DirectionalLight(0xfff5e2,3);sun.position.set(-3,3,5);scene.add(sun);
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',3800)}
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));$('#space').append(renderer.domElement);$('#sceneLoading').remove();renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();toast('三维渲染暂时中断，请刷新页面；知识正文仍可阅读。')});}catch(e){$('#sceneLoading').textContent='当前设备无法显示三维图形，下方知识档案仍可阅读。';}
let seed=157;function random(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}
const stars=new THREE.BufferGeometry(),starPositions=[];for(let i=0;i<1500;i++)starPositions.push((random()-.5)*100,(random()-.5)*80,-15-random()*55);stars.setAttribute('position',new THREE.Float32BufferAttribute(starPositions,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:0xcadcf5,size:.033,transparent:true,opacity:.68})));
const textures=new Map(),loader=new THREE.TextureLoader();function textureFor(name,mat){if(textures.has(name)){mat.map=textures.get(name);mat.color.set('white');mat.needsUpdate=true;return}loader.load('./assets/'+name+'.jpg',tex=>{tex.colorSpace=THREE.SRGBColorSpace;textures.set(name,tex);if(mat.userData.disposed)return;mat.map=tex;mat.color.set('white');mat.needsUpdate=true},undefined,()=>toast('一张图像暂时未能加载，已保留简化模型。'))}
function clearGlobe(){while(globe.children.length){const child=globe.children[0];globe.remove(child);child.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of(Array.isArray(o.material)?o.material:[o.material])){m.userData.disposed=true;m.dispose()}})}globe.rotation.set(0,0,0)}
function sphere(radius,color,emissive=0){const m=new THREE.Mesh(new THREE.SphereGeometry(radius,64,48),new THREE.MeshStandardMaterial({color,roughness:.86,emissive:color,emissiveIntensity:emissive}));globe.add(m);return m}
function ring(inner,outer,color,opacity=.7){const m=new THREE.Mesh(new THREE.RingGeometry(inner,outer,120),new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide,transparent:true,opacity}));m.rotation.x=1.06;m.rotation.y=.18;globe.add(m);return m}
function points(positions,colors,size){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const p=new THREE.Points(geo,new THREE.PointsMaterial({size,vertexColors:true,transparent:true,opacity:.9}));globe.add(p);return p}
function buildObject(o){clearGlobe();$('#space').setAttribute('aria-label',o.name+'科普三维示意，可拖动旋转，使用滚轮或双指缩放');
 if(o.kind==='galaxy'){const pos=[],col=[];for(let i=0;i<6500;i++){const r=Math.pow(random(),.7)*2.6,ang=r*2.1+(i%4)*Math.PI/2+(random()-.5)*.48;pos.push(Math.cos(ang)*r,(random()-.5)*(.16+.14/(r+.15)),Math.sin(ang)*r);const c=new THREE.Color().setHSL(.6+r*.035,.3,.7+random()*.2);col.push(c.r,c.g,c.b)}points(pos,col,.024).rotation.x=.48;globe.rotation.z=-.22;sphere(.13,'#ffe5bd',1)}
 else if(o.kind==='web'||o.kind==='universe'){const pos=[],cols=[],nodes=[];for(let i=0;i<95;i++){const p=new THREE.Vector3((random()-.5)*4.7,(random()-.5)*3.5,(random()-.5)*3.2);nodes.push(p);pos.push(p.x,p.y,p.z);cols.push(.65,.82,.9)}points(pos,cols,.06);const lines=[];nodes.forEach((n,i)=>nodes.forEach((q,j)=>{if(j>i&&n.distanceTo(q)<1.15)lines.push(n.x,n.y,n.z,q.x,q.y,q.z)}));const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(lines,3));globe.add(new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color:0x6d9daa,transparent:true,opacity:.25})));if(o.kind==='universe')globe.add(new THREE.Mesh(new THREE.SphereGeometry(2.8,24,18),new THREE.MeshBasicMaterial({color:0x88c1d2,wireframe:true,transparent:true,opacity:.075})))}
 else if(o.kind==='nebula'){const mat=new THREE.MeshBasicMaterial({color:'white',side:THREE.DoubleSide});textureFor('carina',mat);globe.add(new THREE.Mesh(new THREE.PlaneGeometry(4.8,2.78),mat))}
 else if(o.kind==='blackhole'){sphere(.8,'#000000');for(let i=0;i<20;i++)ring(.92+i*.065,.95+i*.065,new THREE.Color().setHSL(.075,.7,.64-i*.013),.75-i*.024);globe.add(new THREE.Mesh(new THREE.RingGeometry(.82,.88,100),new THREE.MeshBasicMaterial({color:0xffd0a4,side:THREE.DoubleSide})))}
 else{const m=sphere(o.kind==='dwarf'?.85:o.kind==='ring'?1.15:1.55,o.color,o.kind==='star'?.8:o.kind==='dwarf'?.65:0);if(o.texture)textureFor(o.texture,m.material);if(o.id==='earth'){globe.add(new THREE.Mesh(new THREE.SphereGeometry(1.58,64,48),new THREE.MeshBasicMaterial({color:0x4a98d0,transparent:true,opacity:.12,side:THREE.BackSide})));globe.rotation.z=.15}if(o.kind==='ring'){for(let i=0;i<12;i++)ring(1.5+i*.064,1.546+i*.064,i%3?'#bfa887':'#837467',.65);globe.rotation.z=-.19}}}
function setZoom(z){zoom=Math.max(.55,Math.min(1.75,z));camera.position.z=8.6/zoom;$('#zoomValue').textContent=zoom.toFixed(1)+'×'}
function selectObject(id){const o=objects.find(x=>x.id===id);if(!o)throw new Error('未找到这个探索目标');selected=id;group=o.group;$$('.chapter').forEach(b=>{b.classList.toggle('active',b.dataset.group===group);b.setAttribute('aria-pressed',b.dataset.group===group)});renderDock();setZoom(1);buildObject(o);$('#objectName').textContent=o.name;$('#objectEnglish').textContent=o.en;$('#sceneLocation').textContent=o.location;$('#objectSubtitle').textContent=o.subtitle;$('#detailTitle').textContent=o.title;$('#objectIntro').textContent=o.intro;const same=objects.filter(x=>x.group===group);$('#objectIndex').textContent=String(same.indexOf(o)+1).padStart(2,'0')+' / '+String(same.length).padStart(2,'0');$('#facts').innerHTML=o.facts.map(([k,v])=>`<div class="fact"><span>${k}</span><strong>${v}</strong></div>`).join('');$('#readNumber').textContent=o.name+' · 完整档案';$('#article').innerHTML=`<div class="article-head"><h2>${o.lead}</h2><p>${o.body}</p></div><div class="article-columns">${o.sections.map(([h,p])=>`<section><h3>${h}</h3><p>${p}</p></section>`).join('')}</div><div class="note">${o.note}</div>${o.kind==='nebula'?'<figure class="nebula-photo"><img src="./assets/carina.jpg" alt="韦布望远镜近红外观测：船底座星云宇宙悬崖" loading="lazy"><figcaption>近红外观测着色图像 · <a href="https://esawebb.org/images/weic2205a/" target="_blank" rel="noopener">NASA, ESA, CSA, and STScI</a></figcaption></figure>':''}<p class="article-source">延伸阅读：<a href="${o.source}" target="_blank" rel="noopener">${o.kind==='nebula'?'ESA / Webb 观测资料':'NASA Science 科学档案'}</a> · 数据为近似值 · <a href="./credits.html">图像与组件署名</a></p>`;history.replaceState(null,'','#'+id)}
function renderDock(){$('#objectList').innerHTML=objects.filter(x=>x.group===group).map(o=>`<button class="object-btn ${o.id===selected?'active':''}" data-id="${o.id}" aria-pressed="${o.id===selected}"><i style="--body-color:${o.color}" aria-hidden="true"></i><span>${o.name}<small>${o.en}</small></span></button>`).join('');$$('.object-btn').forEach(b=>b.onclick=()=>selectObject(b.dataset.id))}
function showView(name){if(!['explore','timeline','library'].includes(name))throw new Error('无效页面');$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));$$('.nav').forEach(b=>{b.classList.toggle('active',b.dataset.view===name);b.setAttribute('aria-current',b.dataset.view===name?'page':'false')});window.scrollTo({top:0});resize()}
$$('.chapter').forEach(b=>b.onclick=()=>selectObject(objects.find(o=>o.group===b.dataset.group).id));$$('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('#timelineList').innerHTML=timeline.map(([time,title,text],i)=>`<article class="timeline-event"><time>${time}</time><div><span class="eyebrow">CHAPTER ${String(i+1).padStart(2,'0')}</span><h2>${title}</h2><p>${text}</p></div></article>`).join('')+'<p class="article-source">时间范围为科普近似 · <a href="https://science.nasa.gov/universe/overview/" target="_blank" rel="noopener">NASA · 宇宙演化</a></p>';
function renderKnowledge(query=''){const entries=knowledge.filter(e=>e.join('').toLowerCase().includes(query.toLowerCase()));$('#knowledgeGrid').innerHTML=entries.length?entries.map(([tag,title,text,more])=>`<article class="knowledge-card"><span class="eyebrow">${tag}</span><h2>${title}</h2><p>${text}</p><details><summary>再了解一点</summary><p>${more}</p></details></article>`).join(''):'<p class="note">没有匹配的档案。试试“恒星”“生命”或“距离”。</p>'}$('#search').oninput=e=>renderKnowledge(e.target.value.trim());renderKnowledge();
function resize(){if(!renderer)return;const el=$('#space');if(!el.clientWidth||!el.clientHeight)return;camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)}new ResizeObserver(resize).observe($('#space'));resize();
const pointers=new Map();let pinchDistance=0;$('#space').addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});$('#space').setPointerCapture(e.pointerId);if(pointers.size===2){const[a,b]=[...pointers.values()];pinchDistance=Math.hypot(a.x-b.x,a.y-b.y)}});$('#space').addEventListener('pointermove',e=>{const previous=pointers.get(e.pointerId);if(!previous)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){globe.rotation.y+=(e.clientX-previous.x)*.005;globe.rotation.x=Math.max(-1.2,Math.min(1.2,globe.rotation.x+(e.clientY-previous.y)*.005))}else if(pointers.size===2){const[a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinchDistance>0)setZoom(zoom*d/pinchDistance);pinchDistance=d}});for(const type of['pointerup','pointercancel','lostpointercapture'])$('#space').addEventListener(type,e=>{pointers.delete(e.pointerId);pinchDistance=0});$('#space').addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom*Math.exp(-Math.max(-100,Math.min(100,e.deltaY))*.0015))},{passive:false});
let last=0;function tick(t){requestAnimationFrame(tick);const dt=Math.min((t-last)/1000,.05);last=t;if(document.hidden||!$('#explore').classList.contains('active'))return;if(rotating&&!pointers.size&&objects.find(o=>o.id===selected).kind!=='nebula')globe.rotation.y+=dt*.045;if(renderer)renderer.render(scene,camera)}
$('#zoomIn').onclick=()=>setZoom(zoom*1.15);$('#zoomOut').onclick=()=>setZoom(zoom/1.15);$('#resetBtn').onclick=()=>{setZoom(1);globe.rotation.set(0,0,0)};function rotateLabel(){$('#rotateBtn').textContent=rotating?'暂停自转':'继续自转';$('#rotateBtn').setAttribute('aria-pressed',String(rotating))}$('#rotateBtn').onclick=()=>{rotating=!rotating;rotateLabel()};rotateLabel();
$('#aboutBtn').onclick=()=>$('#about').showModal();$$('[data-close]').forEach(x=>x.onclick=()=>document.getElementById(x.dataset.close).close());$('#readMore').onclick=()=>$('#reading').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});
setupHandControls({onZoom:delta=>{if($('#explore').classList.contains('active'))setZoom(zoom*Math.exp(delta))},toast});
const initial=location.hash.slice(1);selectObject(objects.some(o=>o.id===initial)?initial:'earth');requestAnimationFrame(tick);
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea')||$('dialog[open]'))return;if(e.key==='+'||e.key==='=')setZoom(zoom*1.1);if(e.key==='-')setZoom(zoom/1.1);if(e.key==='0')$('#resetBtn').click()});
try{const registered=document.modelContext?.registerTool({name:'explore_cosmic_object',title:'探索宇宙天体',description:'打开指定天体的三维示意和知识档案，不开启摄像头。',inputSchema:{type:'object',properties:{id:{type:'string',enum:objects.map(o=>o.id)}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='id')||!objects.some(o=>o.id===input.id))throw new Error('无效天体');showView('explore');selectObject(input.id);return{id:selected,title:objects.find(o=>o.id===selected).name}}});Promise.resolve(registered).catch(()=>{})}catch(e){}
