import{classifyHand,createGestureFilter}from'./gesture.js';
export function setupHandControls({onZoom,toast}){
const $=s=>document.querySelector(s),dialog=$('#cameraDialog'),video=$('#cameraVideo'),overlay=$('#handOverlay'),ctx=overlay.getContext('2d'),status=$('#cameraStatus'),start=$('#cameraStart'),pill=$('#cameraPill'),filter=createGestureFilter();
let stream=null,model=null,active=false,generation=0,timer=0,starting=false,lastFrame=-1,lastTick=0;
const lines=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[0,17],[17,18],[18,19],[19,20]];
function setStatus(s){status.textContent=s}
function stop(message='摄像头已关闭。'){generation++;active=false;starting=false;clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());stream=null;video.pause();video.srcObject=null;model?.close();model=null;filter.reset();ctx.clearRect(0,0,480,360);start.hidden=false;start.disabled=false;start.textContent='允许摄像头并开始';$('#cameraMinimize').hidden=true;pill.hidden=true;setStatus(message)}
function draw(points){ctx.clearRect(0,0,480,360);if(!points)return;ctx.strokeStyle='#a0e6d0';ctx.lineWidth=2;for(const[a,b]of lines){ctx.beginPath();ctx.moveTo(points[a].x*480,points[a].y*360);ctx.lineTo(points[b].x*480,points[b].y*360);ctx.stroke()}ctx.fillStyle='#fff';for(const p of points){ctx.beginPath();ctx.arc(p.x*480,p.y*360,3,0,Math.PI*2);ctx.fill()}}
function infer(){if(!active)return;const now=performance.now();try{if(video.readyState>=2&&video.currentTime!==lastFrame){lastFrame=video.currentTime;const result=model.detectForVideo(video,now),hands=result.landmarks,g=filter.update(hands.length>1?'multiple':hands.length===1?classifyHand(result.worldLandmarks?.[0]||hands[0]):'none');draw(hands.length===1?hands[0]:null);const dt=Math.min((now-lastTick)/1000,.15);lastTick=now;if(g==='open')onZoom(dt*.52);if(g==='closed')onZoom(-dt*.52);const msg={open:'张开手掌 · 正在拉近',closed:'握拳 · 正在拉远',neutral:'保持半握 · 停止缩放',none:'未检测到手 · 请将单手完整放入画面',multiple:'检测到多只手 · 请只保留一只手'}[g];setStatus(msg);pill.textContent=msg+' · 管理摄像头'}}catch(e){stop('识别暂时中断，请重试或使用鼠标、触屏。');toast('手势识别已停止，仍可使用普通控制。');return}timer=setTimeout(infer,85)}
async function begin(){if(starting||active)return;if(!window.isSecureContext){setStatus('摄像头需要 HTTPS 安全连接，请使用发布链接打开。');return}if(!navigator.mediaDevices?.getUserMedia){setStatus('当前浏览器不支持摄像头，请在 Chrome、Edge 或 Safari 中打开。');return}starting=true;const ticket=++generation;start.disabled=true;setStatus('等待摄像头授权…');try{const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:480},height:{ideal:360},frameRate:{ideal:15,max:24}},audio:false});if(ticket!==generation){media.getTracks().forEach(t=>t.stop());return}stream=media;video.srcObject=stream;await video.play();if(ticket!==generation)return;stream.getVideoTracks()[0].addEventListener('ended',()=>{if(active||starting)stop('摄像头连接已结束。')},{once:true});setStatus('正在加载本地手部识别模型，首次可能需要片刻…');const{FilesetResolver,HandLandmarker}=await import('./vendor/vision_bundle.mjs');const files=await FilesetResolver.forVisionTasks(new URL('./vendor/wasm/',import.meta.url).href.replace(/\/$/,''));if(ticket!==generation)return;let created;const options={baseOptions:{modelAssetPath:new URL('./vendor/hand_landmarker.task',import.meta.url).href,delegate:'GPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.6,minHandPresenceConfidence:.6,minTrackingConfidence:.6};try{created=await HandLandmarker.createFromOptions(files,options)}catch(e){if(ticket!==generation)return;options.baseOptions.delegate='CPU';created=await HandLandmarker.createFromOptions(files,options)}if(ticket!==generation){created.close();return}model=created;active=true;starting=false;lastFrame=-1;lastTick=performance.now();filter.reset();start.hidden=true;$('#cameraMinimize').hidden=false;pill.hidden=false;setStatus('模型已准备好，请举起一只手。');infer()}catch(e){if(ticket!==generation)return;const messages={NotAllowedError:'未获得摄像头权限。请在浏览器网站设置中允许后重试。',NotFoundError:'未找到摄像头。可以连接摄像头，或继续用鼠标、触屏探索。',NotReadableError:'摄像头可能被其他应用占用，请关闭占用它的应用后重试。',OverconstrainedError:'摄像头不支持当前配置，请尝试其他浏览器。'};stop(messages[e.name]||'模型或摄像头加载失败，请检查网络后重试。普通操作不受影响。')}}
$('#cameraBtn').onclick=()=>dialog.showModal();pill.onclick=()=>dialog.showModal();start.onclick=begin;$('#cameraClose').onclick=()=>{stop();dialog.close()};$('#cameraMinimize').onclick=()=>dialog.close();dialog.addEventListener('cancel',()=>stop());dialog.addEventListener('close',()=>{if(starting)stop()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&(active||starting))stop('页面进入后台，摄像头已自动关闭。')});window.addEventListener('pagehide',()=>stop());
}
